name: intro_flutter
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: 3.7.4

dependencies:
  bloc: ^8.1.1
  character_repository:
    path: packages/character_repository
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  rick_and_morty_api:
    path: packages/rick_and_morty_api

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  mocktail_image_network: ^0.3.1
  very_good_analysis: 4.0.0+1

flutter:
  uses-material-design: true
  generate: true
