name: intro_flutter
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: 2.10.0

dependencies:
  bloc: ^8.0.3
  character_repository:
    path: packages/character_repository
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  rick_and_morty_api:
    path: packages/rick_and_morty_api

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  mocktail_image_network: ^0.3.1
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
