name: intro_flutter
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^7.0.0
  character_repository:
    path: packages/character_repository
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  rick_and_morty_api:
    path: packages/rick_and_morty_api

dev_dependencies:
  bloc_test: ^8.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.0
  mocktail_image_network: ^0.1.0
  very_good_analysis: ^2.3.0

flutter:
  uses-material-design: true
  generate: true
