name: character_repository
description: Dart package for the character domain
publish_to: none
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: ^2.0.5
  rick_and_morty_api:
    path: ../rick_and_morty_api

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.23.1
  very_good_analysis: ^4.0.0+1
