name: character_repository
on:
  pull_request:
    paths:
      - "packages/character_repository/**"
      - ".github/workflows/character_repository.yaml"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
