name: rick_and_morty_api
on:
  pull_request:
    paths:
      - "packages/rick_and_morty_api/**"
      - ".github/workflows/rick_and_morty_api.yaml"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
